default: &default
  adapter: sqlite3

development:
  <<: *default
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
