default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOST"] || 'localhost' %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: viaje_development
test:
  <<: *default
  database: viaje_test
production:
  <<: *default
  database: viaje_production
  host: <%= ENV["DB_HOST"] || 'localhost' %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

